#!/usr/bin/env bash
# Mullvad integration verifier.
#
# Assumes deploy/docker-compose.mullvad.yml is already running (the
# Makefile test-integration target and the CI mullvad-integration job
# both bring the stack up before invoking this script). Then for each
# configured country: writes a one-country tunnelsmith.mullvad.toml,
# restarts the tunnelsmith container, and curls am.i.mullvad.net/json
# through the proxy to confirm the returned `country` matches.
#
# Per ADR-001 this script runs in CI, not on developer hosts. The
# integration job in .github/workflows/ci.yml gates on both
# MULLVAD_WIREGUARD_PRIVATE_KEY and MULLVAD_WIREGUARD_ADDRESSES being
# set as repo secrets. Without those secrets the job logs a [skip-ok]
# reason and exits 0 before this script ever runs.
#
# Exit codes:
#   0  every country verified
#   1  verification failed (country mismatch, curl error, or jq parse error)
#   2  tunnelsmith never became ready in time
#   3  VERIFY_COUNTRIES is empty or invalid after trimming
#   4  a required external tool (jq, curl, docker) is missing

set -euo pipefail

require_command() {
  for cmd in "$@"; do
    if ! command -v "${cmd}" >/dev/null 2>&1; then
      echo "verify-mullvad: required command not found: ${cmd}" >&2
      exit 4
    fi
  done
}

require_command jq curl docker

COMPOSE_FILE="${COMPOSE_FILE:-deploy/docker-compose.mullvad.yml}"
CONFIG_FILE="${CONFIG_FILE:-deploy/tunnelsmith.mullvad.toml}"
VERIFY_COUNTRIES="${VERIFY_COUNTRIES:-Sweden,Netherlands,USA}"
SOCKS_HOST="${SOCKS_HOST:-localhost}"
SOCKS_PORT="${SOCKS_PORT:-1080}"
READY_TIMEOUT_S="${READY_TIMEOUT_S:-90}"

# VERIFY_COUNTRIES is a comma-separated list. Split it, then trim each
# element so values like "Sweden, Netherlands, USA" do not produce country
# names with leading spaces (which would never match the Mullvad relay
# list and silently expand to zero upstreams).
IFS=',' read -r -a RAW_COUNTRY_LIST <<<"${VERIFY_COUNTRIES}"
COUNTRY_LIST=()
for raw in "${RAW_COUNTRY_LIST[@]}"; do
  trimmed="${raw#"${raw%%[![:space:]]*}"}"   # strip leading whitespace
  trimmed="${trimmed%"${trimmed##*[![:space:]]}"}" # strip trailing whitespace
  if [ -n "${trimmed}" ]; then
    COUNTRY_LIST+=("${trimmed}")
  fi
done
if [ "${#COUNTRY_LIST[@]}" -eq 0 ]; then
  echo "VERIFY_COUNTRIES yielded no usable entries after trimming: ${VERIFY_COUNTRIES}" >&2
  exit 3
fi

write_config() {
  local country="$1"
  cat > "${CONFIG_FILE}" <<EOF
# Generated by scripts/verify-mullvad.sh; do not edit by hand.
[listener]
http  = ":8080"
socks = ":1080"

[failure]
timeout_ms              = 8000
max_retries_per_request = 3

[[upstream_pool]]
provider  = "mullvad"
id_prefix = "mvd"
countries = ["${country}"]
EOF
}

restart_tunnelsmith() {
  docker compose -f "${COMPOSE_FILE}" restart tunnelsmith >/dev/null
}

wait_ready() {
  local deadline=$(( SECONDS + READY_TIMEOUT_S ))
  while (( SECONDS < deadline )); do
    if curl -fsS --socks5-hostname "${SOCKS_HOST}:${SOCKS_PORT}" \
        --connect-timeout 5 --max-time 10 \
        -o /dev/null https://am.i.mullvad.net/connected; then
      return 0
    fi
    sleep 3
  done
  return 1
}

verify_country() {
  local expected="$1"
  local body
  # Capture curl failures explicitly so a transient SOCKS5 hiccup or
  # am.i.mullvad.net timeout exits with the documented code 1 ("a country
  # mismatched expectations") rather than letting `set -e` propagate
  # curl's exit status. Same for the two jq calls below.
  if ! body=$(curl -fsS --socks5-hostname "${SOCKS_HOST}:${SOCKS_PORT}" \
      --connect-timeout 10 --max-time 20 \
      https://am.i.mullvad.net/json); then
    echo "verify failed: curl could not reach am.i.mullvad.net through tunnelsmith for ${expected}" >&2
    return 1
  fi
  local got_country got_exit
  if ! got_country=$(printf '%s' "${body}" | jq -r .country); then
    echo "verify failed: jq could not parse country from am.i.mullvad.net response for ${expected}" >&2
    echo "${body}" >&2
    return 1
  fi
  if ! got_exit=$(printf '%s' "${body}" | jq -r .mullvad_exit_ip); then
    echo "verify failed: jq could not parse mullvad_exit_ip from am.i.mullvad.net response for ${expected}" >&2
    echo "${body}" >&2
    return 1
  fi
  if [[ "${got_exit}" != "true" ]]; then
    echo "verify failed: am.i.mullvad.net says we are not exiting through Mullvad" >&2
    echo "${body}" | jq . >&2
    return 1
  fi
  if [[ "${got_country}" != "${expected}" ]]; then
    echo "verify failed: expected ${expected}, got ${got_country}" >&2
    echo "${body}" | jq . >&2
    return 1
  fi
  echo "ok: ${expected}"
}

main() {
  echo "verify-mullvad: countries = ${COUNTRY_LIST[*]}"
  for country in "${COUNTRY_LIST[@]}"; do
    echo "--- verifying ${country} ---"
    write_config "${country}"
    restart_tunnelsmith
    if ! wait_ready; then
      echo "tunnelsmith did not respond on ${SOCKS_HOST}:${SOCKS_PORT} within ${READY_TIMEOUT_S}s" >&2
      docker compose -f "${COMPOSE_FILE}" logs tunnelsmith | tail -50 >&2 || true
      exit 2
    fi
    verify_country "${country}"
  done
  echo "--- all countries verified ---"
}

main "$@"
